# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-hmac}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daiki Ueno", "Geoffrey Grosenbach", "Brian Clubb"]
  s.date = %q{2009-08-07}
  s.description = %q{A MAC provides a way to check the integrity of information transmitted over or stored in an unreliable medium, based on a secret key.}
  s.email = %q{bclubb@gmail.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "lib/hmac-md5.rb",
     "lib/hmac-rmd160.rb",
     "lib/hmac-sha1.rb",
     "lib/hmac-sha2.rb",
     "lib/hmac.rb"
  ]
  s.homepage = %q{http://www.github.com/bclubb/ruby-hmac}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An implementation of the HMAC authentication code in Ruby.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
